import Layout from '@/components/Layout';
import Navbar from '@/components/Navbar';
import Sidebar from '@/components/Sidebar/Sidebar';
import Head from 'next/head';


const Home: React.FC = () => {
    return (
        <Layout>
            <Head>
                <title>Home Page</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <div className="container mx-auto">
                <Navbar />
                <div className="flex">
                    <Sidebar />
                    <main className="flex-1 p-4">
                        <h1 className="text-2xl font-bold">Welcome to Home Page</h1>
                    </main>
                </div>
            </div>
        </Layout>
    );
};

export default Home;
