import Layout from '@/components/Layout';
import Navbar from '@/components/Navbar';
import NonProfiteHeader from '@/components/NonHeader/NonProfiteHeader';
import Profile from '@/components/Profile/Profile';
import Sidebar from '@/components/Sidebar/Sidebar';
import Head from 'next/head';



const Home: React.FC = () => {
  return (
    <Layout >
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="container mx-auto" >
        <div style={{ display: "flex" }}>
          <aside>
            <Sidebar />
          </aside>
          <main>
            <NonProfiteHeader />
          </main>
          <article>
            <Profile />
          </article>
        </div>
      </div>
    </Layout>
  );
};

export default Home;
//#F7FAFF

